kind: Kustomization

namespace: argocd-stresstest

resources:
- appset.yaml
- argocd.yaml
- namespace.yaml
- secret.yaml

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
    name: stresstest
  patch: |-
    - op: replace
      path: /spec/generators/0/git/repoURL
      value: ssh://git@...
- target:
    group: argoproj.io
    version: v1beta1
    kind: ArgoCD
    name: argocd
  patch: |-
    - op: replace
      path: /spec/sso/dex/groups
      value:
        - SOME-GROUP
    - op: replace
      path: /spec/initialSSHKnownHosts/keys
      value: |
        github.com ssh-rsa ....
    - op: replace
      path: /spec/rbac/policy
      value: |
        g, SOME-GROUP
- target:
    version: v1
    kind: Secret
    name: my-repo
  patch: |-
    - op: replace
      path: /stringData/sshPrivateKey
      value: xxx
    - op: replace
      path: /stringData/url
      value: ssh://...